/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Author:  User
 * Created: 22-abr-2019
 */
DROP TABLE GENERO;
DROP TABLE PELICULA;

CREATE TABLE GENERO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(5000),
    FOTO VARCHAR(500),
    CONSTRAINT ID_GENERO_PK PRIMARY KEY (ID)
);

CREATE TABLE PELICULA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(30) NOT NULL,
    GENERO INTEGER NOT NULL,
    PRESUPUESTO DECIMAL(15,2),
    PRODUCTORA VARCHAR(30),
    DURACION INTEGER,
    DIRECTOR VARCHAR(50),
    SINOPSIS VARCHAR(10000),
    ESTRENO BOOLEAN,
    FECHA DATE,
    CONSTRAINT ID_PELICULA_PK PRIMARY KEY (ID),
    CONSTRAINT GENERO_PELICULA_FK FOREIGN KEY (GENERO) REFERENCES GENERO (ID)
); 